language: generic
  
cache:
  yarn: true
  directories:
  - node_modules

matrix:
  include:
    - env: PROJECT=src/private/
      node_js: "10.16.3"

install:
  - cd $PROJECT
  - yarn global add serverless
  - yarn install

script:
  - cd $PROJECT
  - yarn test
  - yarn build  

deploy:
  provider: script
  script:
    - yarn deploy
  skip_cleanup: true
#on:
# branch: master