org: yourwishes
service: domsplace

frameworkVersion: ">=1.26.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, "test"}
  region: ap-southeast-2
  memorySize: 512
    
package:
  excludeDevDependencies: false
  individually: true
  include:
    - public/**

plugins:
  - serverless-plugin-include-dependencies
  - serverless-finch

custom:
  client:
    bucketName: domsplace-${self:provider.stage}-${self:provider.region}-public
    distributionFolder: public/
    indexDocument: index.html
    errorDocument: index.html